/*
  # Fix RLS Policies with Session-Based Access Control

  ## Overview
  This migration replaces the insecure "always true" RLS policies with session-based
  access control. Since the app doesn't use authentication, we use a session_id to
  associate data with specific browser sessions.

  ## Changes

  1. Schema Changes
    - Add `session_id` column (TEXT) to `study_plans` table
    - This column stores a unique identifier generated by the client

  2. Security Changes
    - Drop existing insecure policies that use `USING (true)`
    - Create new restrictive policies that check session_id via request headers
    - Policies use `current_setting('request.headers')::json->>'x-session-id'` to get
      the session ID from the request

  3. Policy Details
    - study_plans: Users can only access plans matching their session_id
    - subjects: Access granted if the parent plan belongs to the user's session
    - day_tasks: Access granted if the parent plan belongs to the user's session

  ## Notes
    - The session_id is passed via the `x-session-id` HTTP header from the client
    - Existing data without session_id will need to be associated with a session
*/

-- Add session_id column to study_plans
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' 
    AND table_name = 'study_plans' 
    AND column_name = 'session_id'
  ) THEN
    ALTER TABLE public.study_plans ADD COLUMN session_id TEXT;
  END IF;
END $$;

-- Create index for session_id lookups
CREATE INDEX IF NOT EXISTS idx_study_plans_session_id ON public.study_plans(session_id);

-- Drop existing insecure policies
DROP POLICY IF EXISTS "Allow all access to study_plans" ON public.study_plans;
DROP POLICY IF EXISTS "Allow all access to subjects" ON public.subjects;
DROP POLICY IF EXISTS "Allow all access to day_tasks" ON public.day_tasks;

-- Create a function to get session_id from request headers safely
CREATE OR REPLACE FUNCTION public.get_session_id()
RETURNS TEXT
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  headers_raw TEXT;
  headers_json JSONB;
BEGIN
  BEGIN
    headers_raw := current_setting('request.headers', true);
    IF headers_raw IS NULL OR headers_raw = '' THEN
      RETURN NULL;
    END IF;
    headers_json := headers_raw::jsonb;
    RETURN headers_json->>'x-session-id';
  EXCEPTION WHEN OTHERS THEN
    RETURN NULL;
  END;
END;
$$;

-- study_plans policies
CREATE POLICY "Users can view their own study plans"
  ON public.study_plans
  FOR SELECT
  USING (session_id = public.get_session_id());

CREATE POLICY "Users can insert their own study plans"
  ON public.study_plans
  FOR INSERT
  WITH CHECK (session_id = public.get_session_id());

CREATE POLICY "Users can update their own study plans"
  ON public.study_plans
  FOR UPDATE
  USING (session_id = public.get_session_id())
  WITH CHECK (session_id = public.get_session_id());

CREATE POLICY "Users can delete their own study plans"
  ON public.study_plans
  FOR DELETE
  USING (session_id = public.get_session_id());

-- subjects policies (based on parent plan's session_id)
CREATE POLICY "Users can view subjects of their plans"
  ON public.subjects
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.study_plans
      WHERE study_plans.id = subjects.plan_id
      AND study_plans.session_id = public.get_session_id()
    )
  );

CREATE POLICY "Users can insert subjects to their plans"
  ON public.subjects
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.study_plans
      WHERE study_plans.id = subjects.plan_id
      AND study_plans.session_id = public.get_session_id()
    )
  );

CREATE POLICY "Users can update subjects of their plans"
  ON public.subjects
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.study_plans
      WHERE study_plans.id = subjects.plan_id
      AND study_plans.session_id = public.get_session_id()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.study_plans
      WHERE study_plans.id = subjects.plan_id
      AND study_plans.session_id = public.get_session_id()
    )
  );

CREATE POLICY "Users can delete subjects of their plans"
  ON public.subjects
  FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.study_plans
      WHERE study_plans.id = subjects.plan_id
      AND study_plans.session_id = public.get_session_id()
    )
  );

-- day_tasks policies (based on parent plan's session_id)
CREATE POLICY "Users can view tasks of their plans"
  ON public.day_tasks
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.study_plans
      WHERE study_plans.id = day_tasks.plan_id
      AND study_plans.session_id = public.get_session_id()
    )
  );

CREATE POLICY "Users can insert tasks to their plans"
  ON public.day_tasks
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.study_plans
      WHERE study_plans.id = day_tasks.plan_id
      AND study_plans.session_id = public.get_session_id()
    )
  );

CREATE POLICY "Users can update tasks of their plans"
  ON public.day_tasks
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.study_plans
      WHERE study_plans.id = day_tasks.plan_id
      AND study_plans.session_id = public.get_session_id()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.study_plans
      WHERE study_plans.id = day_tasks.plan_id
      AND study_plans.session_id = public.get_session_id()
    )
  );

CREATE POLICY "Users can delete tasks of their plans"
  ON public.day_tasks
  FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.study_plans
      WHERE study_plans.id = day_tasks.plan_id
      AND study_plans.session_id = public.get_session_id()
    )
  );